## Data representations for neural networks
**Author:** Karen Mazidi
**Date:** 11.4.2021

NumPy arrays can be used as input data in TensorFlow. We can also use Tensorflow tensors as input. 

However, there are some advantages of Tensors over arrays:

* tensors are immutable which makes for faster architecture
* highly optimized under the hood
* tensors make parallelization easier because they can reside in GPU memory
* tensors support autodifferentiation
* models using tensors can be written for TF Light on mobile devices


#### Attributes

NumPy arrays and TF tensors are known by their shape or rank, as well as their data types. 

### TF variables and constants

tf.constant creates a tensor from a tensor-like object

```
tf.constant(value, dtype-None, shape=None, name='Const')
```

This constructor performs essentially the same functionality as tf.convert_to_tensor. 

The dtype and shape will be inferred from the value if they are not specified. 

tf.Variable must be initialized when constructed. The initial value defines the type and shape of the variable. The type and shape cannot be changed but the value can. Construct:

```
tf.Variable(initial_value=None, trainable=None, dtype=None)
```

### TF Tensors

A key difference between tf.Variable and tf.Tensor is that tensors are immutable and variables are variable. If you perform an operation on a tensor, a  new tensor is returned, rather than updating the tensor in place.

Read more about tensors [in the docs](https://www.tensorflow.org/guide/tensor)








### Scalars (rank-0 tensors)

In [1]:
import numpy as np
import tensorflow as tf

In [ ]:
# numpy

arr0 = np.array(42)
print('shape=', arr0.shape)

shape= ()


In [ ]:
# TF

t0 = tf.constant(0)
print('shape=', t0.shape)

shape= ()


In [ ]:
# note this is different from:

tf.constant([0]).shape

TensorShape([1])

### Vectors (rank-1 tensors)

Both NumPy and TF will infer the data type from the data unless you specify parameter data=)

In [ ]:
arr1 = np.array([1, 2, 3])
arr1
print('shape=', arr1.shape)
print('type=', arr1.dtype)

shape= (3,)
type= int64


In [ ]:
t1 = tf.constant([1, 2, 3.0])
print('shape=', t1.shape)
print('type=', t1.dtype)

shape= (3,)
type= <dtype: 'float32'>


### Matrices (rank-2 tensors)

NumPy supports reshaping. With TF, we can specify the shape as we create the tensor. 

Both have the ndim attribute. 

In [ ]:
x = np.array(range(10), dtype=float)
arr2 = x.reshape(5, 2)
print(arr2)
print('ndim=', arr2.ndim)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
ndim= 2


In [ ]:
t2 = tf.constant(x, shape=(5, 2))
print(t2)
print('ndim=', t2.ndim)

tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]], shape=(5, 2), dtype=float64)
ndim= 2


### Rank-3 and higher-rank tensors

With the dtype parameter in both, you can specify float or int. If you want a specific size, use quotes around the type. 

In [ ]:
x = np.array(range(1,31), dtype='float32')
arr3 = x.reshape(2, 3, 5)
print(arr3)
print('type=', arr3.dtype)
print('ndim=', arr3.ndim)

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]
type= float32
ndim= 3


In [ ]:
t3 = tf.constant(x, shape=(2,3,5), dtype='float64')
print(t3)
print('ndim=', t3.ndim)
print('type=', arr3.dtype)

tf.Tensor(
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]], shape=(2, 3, 5), dtype=float64)
ndim= 3
type= float64




### Size

The size attribute gives the number of elements.

Notice that you have to convert the tensor to numpy to get the size.


In [ ]:
arr2.size

10

In [ ]:
tf.size(t2).numpy()

10

### Converting

Convert between NumPy and TF is possible as shown below:

In [ ]:
arr = t3.numpy()
type(arr)

numpy.ndarray

In [ ]:
t = tf.convert_to_tensor(arr)
type(t)

tensorflow.python.framework.ops.EagerTensor

### More about tf.Variable

In [2]:
v = tf.Variable([1, 2, 3])
v

<tf.Variable 'Variable:0' shape=(3,) dtype=int32_ref>

In [8]:
w = tf.Variable([[1.], [2.]])
x = tf.constant([[3., 4.]])
tf.matmul(w, x)


<tf.Tensor 'MatMul_3:0' shape=(2, 2) dtype=float32>

In [9]:
tf.sigmoid(w + x)

<tf.Tensor 'Sigmoid:0' shape=(2, 2) dtype=float32>

### Explore low-level functions of TensorFlow

Using TensorFlow to create a network involves first defining the "graph", the inputs and outputs, then executing the graph.

#### Eager execution

TensorFlow 2 uses imperative execution, meaning that defining the graph and execution happen at the same time. This is also called Eager execution.

#### AutoGraph and @tf.function

Notice the @tf.function decorator below. A decorator is a wrapper for a function that can alter the function's behavior before or after it executes.

In the code below, the @tf.function decorator will turn the function actions into a data-flow graph. This is called AutoGraph. Read more [in the docs](https://www.tensorflow.org/guide/function#autograph_transformations)

See p. 21 of TensorFlow 2.0 in Action

![Network](network.png)

In [12]:

@tf.function
def forward(x, W, b, act):
  """ Encapsulates the computations of a single layer in a multilayer perceptron """
  return act(tf.matmul(x,W)+b)

# Input (numpy array)
x = np.random.normal(size=[1,4]).astype('float32')

# Variable initializer
init = tf.keras.initializers.RandomNormal()

# Defining layer 1 variables
w1 = tf.Variable(init(shape=[4,3]))
b1 = tf.Variable(init(shape=[1,3]))

# Defining layer 2 variables
w2 = tf.Variable(init(shape=[3,2]))
b2 = tf.Variable(init(shape=[1,2]))

# Computing h
h = forward(x, w1, b1, tf.nn.sigmoid)

# Computing y
y = forward(h, w2, b2, tf.nn.softmax)

print(y)



tf.Tensor([[0.45918176 0.5408183 ]], shape=(1, 2), dtype=float32)
